FROM nerevarishe/vista-portal-backend:dev
WORKDIR /srv/www/vista-portal-backend
COPY . .
EXPOSE 5000
VOLUME /srv/www/vista-portal-backend/static/uploads
CMD gunicorn -w 4 -b 0.0.0.0:5000 vista_portal_api:app
